"""Ask the Agent API a question and show how it was answered.

    python scripts/ask.py "Find customer C001 and tell me their latest order status"
    python scripts/ask.py --trace demo-001 "Show customer C999"     # choose the correlation ID
    python scripts/ask.py --json "Show customer C001"                # full JSON response

Goes through the API gateway like any client (default key: chat-frontend-key).
Standard library only, so it runs anywhere Python 3.8+ is installed.
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request

COLORS = sys.stdout.isatty() and os.name != "nt"
BOLD, DIM, RESET = ("\033[1m", "\033[2m", "\033[0m") if COLORS else ("", "", "")


def main() -> int:
    p = argparse.ArgumentParser(description="Ask the ComCo Agent API")
    p.add_argument("query")
    p.add_argument("--gateway", default=os.getenv("GATEWAY", "http://localhost:8000"))
    p.add_argument("--key", default=os.getenv("API_KEY", "chat-frontend-key"))
    p.add_argument("--trace", help="X-Correlation-ID to send (default: generated by the gateway)")
    p.add_argument("--json", action="store_true", help="print the full JSON response")
    a = p.parse_args()

    headers = {"Content-Type": "application/json", "apikey": a.key}
    if a.trace:
        headers["X-Correlation-ID"] = a.trace
    req = urllib.request.Request(f"{a.gateway}/api/agent/query", method="POST", headers=headers,
                                 data=json.dumps({"query": a.query}).encode())
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            code, body = resp.status, resp.read()
    except urllib.error.HTTPError as e:
        code, body = e.code, e.read()
    except urllib.error.URLError as e:
        print(f"Cannot reach the gateway at {a.gateway}: {e.reason}")
        return 2

    try:
        r = json.loads(body)
    except ValueError:
        print(f"HTTP {code}: {body[:300]!r}")
        return 1
    if a.json or "answer" not in r:
        print(f"HTTP {code}")
        print(json.dumps(r, indent=2, ensure_ascii=False))
        return 0 if code < 400 else 1

    print(f"{BOLD}Q:{RESET} {r['query']}")
    print(f"{BOLD}A:{RESET} {r['answer']}")
    print(f"{DIM}HTTP {code} · status={r['status']} · {r['duration_ms']} ms · correlation-id={r['correlation_id']}{RESET}")
    if r.get("trace_id"):
        print(f"{DIM}Trace: {os.getenv('JAEGER', 'http://localhost:16686')}/trace/{r['trace_id']}{RESET}")
    if r["reasoning"]:
        print(f"{BOLD}Reasoning{RESET}")
        for line in r["reasoning"]:
            print(f"  - {line}")
    if r["steps"]:
        print(f"{BOLD}Steps{RESET}")
        for s in r["steps"]:
            detail = s.get("outcome") or (s.get("error") or {}).get("code") or s.get("reason") or ""
            agent = s.get("agent") or "-"
            print(f"  {s['id']}  {s['skill']:<22} {agent:<15} {s['state']:<9} {detail}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
