"""Export each service's OpenAPI spec to docs/openapi/*.yaml (a submission deliverable).

The specs are generated by FastAPI from the code, so re-run this after changing an API:
    python scripts/export_openapi.py                     # via the gateway (stack running)
    python scripts/export_openapi.py http://localhost:8101 http://localhost:8102 http://localhost:8203  # direct
Requires: pip install httpx pyyaml
"""
import sys
from pathlib import Path

import httpx
import yaml

OUT = Path(__file__).resolve().parent.parent / "docs" / "openapi"

if len(sys.argv) == 4:
    sources = {"customer-api": f"{sys.argv[1]}/customers/openapi.json",
               "order-api": f"{sys.argv[2]}/orders/openapi.json",
               "agent-api": f"{sys.argv[3]}/agent/openapi.json"}
else:
    sources = {"customer-api": "http://localhost:8000/api/customers/openapi.json",
               "order-api": "http://localhost:8000/api/orders/openapi.json",
               "agent-api": "http://localhost:8000/api/agent/openapi.json"}

OUT.mkdir(parents=True, exist_ok=True)
for name, url in sources.items():
    spec = httpx.get(url, timeout=10).raise_for_status().json()
    spec["servers"] = [{"url": "http://localhost:8000/api", "description": "Local API gateway"}]
    path = OUT / f"{name}.yaml"
    path.write_text(yaml.safe_dump(spec, sort_keys=False, allow_unicode=True))
    print(f"wrote {path.relative_to(OUT.parent.parent)}  ({len(spec['paths'])} paths)")
